# Docker Compose
version: '3.3'

# Define services
services:
  # spring service
  app:
    image: ams_spring_app:latest
    ports:
      - "8091:8080"
    container_name: safwen_amsdata_2025_cont
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dbams2024?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: sip
      SPRING_DATASOURCE_PASSWORD: sip-ac2024

  # Database Service (Mysql)
  db:
    image: mysql:8.0
    container_name: mysql_cont
    volumes:
      - safwen_db_ams_vol:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: dbams2024
      MYSQL_USER: sip
      MYSQL_PASSWORD: sip-ac2024
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 20s
      retries: 10

  # phpmyadmin Service
  phpmyadmin:
    image: phpmyadmin
    container_name: pmadmin_saf_cont
    depends_on:
      - db
    restart: always
    ports:
      - "8089:80"
    environment:
      - PMA_ARBITRARY=1

# Volumes
volumes:
  safwen_db_ams_vol:



